import type { Metadata } from "next";
import { NavBar } from "../components";
import "./globals.css";
import { AuthContextProvider } from "../context/AuthContext";


const metadata: Metadata = {
  title: "Inventory Management App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='bg-bgimg'>
        <AuthContextProvider>
          <NavBar />
          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
